apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hypergraph.fullname" . }}-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hypergraph.name" . }}
      app.kubernetes.io/component: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hypergraph.fullname" . }}-explainer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hypergraph.name" . }}
      app.kubernetes.io/component: explainer
